// app/routes/__root.vue
<!-- App.vue - Root component -->
<template>
  <div>
    <!-- Equivalent to Outlet in React Router -->
    <router-view />
  </div>
</template>

<script setup lang="ts">
// No setup logic needed for the base template
</script>

<!-- router/index.ts - Router Configuration -->
<script lang="ts">
import { createRouter, createWebHistory, RouteRecordRaw } from 'vue-router'
import App from '@/App.vue'
import router from '@/router/index'

// Import your app styles
import '../styles/app.css'

// Define routes - you would add your actual routes here
const routes: Array<RouteRecordRaw> = [
  {
    path: '/',
    name: 'Home',
    component: () => import('./index.vue'),
    meta: {
      title: 'DeepSeek Chat'
    }
  }
  // Add other routes here
]

// Create router instance
const router = createRouter({
  history: createWebHistory(),
  routes,
  scrollBehavior(to, from, savedPosition) {
    // Implement scroll restoration (equivalent to ScrollRestoration)
    if (savedPosition) {
      return savedPosition
    } else {
      return { top: 0 }
    }
  }
})

// Handle document title (equivalent to meta title)
router.beforeEach((to, from, next) => {
  document.title = to.meta.title as string || 'DeepSeek Chat'
  next()
})

export default router
</script>

<!-- main.ts - Entry point -->
<script lang="ts">
import { createApp } from 'vue'
import App from './App.vue'
import router from './router'

const app = createApp(App)

// Mount app
app.use(router)
app.mount('#app')
</script>

<!-- index.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DeepSeek Chat</title>
    <link rel="stylesheet" href="/src/styles/app.css" />
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>

// app/routes/__root.tsx
// app/routes/__root.tsx
import { createRootRoute } from "@tanstack/react-router";
import { Outlet, ScrollRestoration } from "@tanstack/react-router";
import { Body, Head, Html, Meta, Scripts } from "@tanstack/start";
import * as React from "react";

import "./index.css";

export const Route = createRootRoute({
  meta: () => [
    {
      charSet: "utf-8",
    },
    {
      name: "viewport",
      content: "width=device-width, initial-scale=1",
    },
    {
      title: "Start + Deepseek + Ollama",
    },
  ],
  component: RootComponent,
});

function RootComponent() {
  return (
    <RootDocument>
      <Outlet />
    </RootDocument>
  );
}

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <Html>
      <Head>
        <Meta />
      </Head>
      <Body>
        {children}
        <ScrollRestoration />
        <Scripts />
      </Body>
    </Html>
  );
}
