// app/routes/index.vue
<!-- index.vue -->
<template>
  <div class="flex flex-col min-h-screen bg-gray-900">
    <!-- Header -->
    <header class="bg-gray-800 border-b border-gray-700 p-4">
      <h1 class="text-xl text-white font-medium">DeepSeek Chat</h1>
    </header>

    <!-- System prompt area -->
    <div class="p-4">
      <div class="bg-gray-800 rounded-lg p-4 border border-gray-700">
        <label class="block text-sm font-medium text-gray-300 mb-2">
          System Prompt:
          <textarea 
            class="mt-2 w-full rounded-md bg-gray-90 border-gray-700 text-gray-100 p-2 text-sm"
            v-model="premise" 
            rows="3"
          />
        </label>
      </div>
    </div>
    
    <!-- Chat area -->
    <div class="flex-1 p-4 pb-32 overflow-y-auto">
      <div v-if="filteredMessages.length === 0" class="flex flex-col items-center justify-center h-48 text-gray-500">
        <div class="bg-gray-800 p-3 rounded-full mb-3">
          <MessageSquare class="h-6 w-6" />
        </div>
        <p>Ask DeepSeek something to start a conversation</p>
      </div>
      
      <AIMessage 
        v-for="(message, index) in filteredMessages" 
        :key="index" 
        :message="message" 
      />
    </div>

    <!-- Input area -->
    <div class="fixed bottom-0 left-0 right-0 p-4 bg-gray-800 border-t border-gray-700">
      <form @submit.prevent="handleSubmit" class="max-w-4xl mx-auto">
        <div class="flex gap-3">
          <div class="flex-1 relative">
            <MessageSquare class="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
            <input
              type="text"
              class="w-full rounded-lg bg-gray-900 border border-gray-700 text-gray-100 pl-10 py-3 pr-4"
              v-model="input"
              :disabled="loading"
              placeholder="Ask your local DeepSeek..."
            />
          </div>
          <button
            type="submit"
            :disabled="loading || !input.trim()"
            class="bg-blue-600 hover:bg-blue-700 disabled:bg-gray-700 text-white px-4 py-2 rounded-lg flex items-center justify-center"
          >
            <Loader2 v-if="loading" class="h-5 w-5 animate-spin" />
            <Send v-else class="h-5 w-5" />
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script>
import { ref, computed } from 'vue';
import { Loader2, MessageSquare, Send } from 'lucide-vue-next';
import AIMessage from '../components/AIMessage.vue';
import Button from '../components/ui/button.vue';
import Input from '../components/ui/input.vue';

export default {
  name: 'AIChat',
  components: {
    AIMessage,
    MessageSquare,
    Loader2,
    Send,
    Button,
    Input
  },
  setup() {
    // Component state
    const messages = ref([]);
    const input = ref('');
    const premise = ref('You are a software developer with a focus on Vue/JavaScript.\rKeep your answer simple and straight forward.');
    const loading = ref(false);

    // Function to process messages and extract thinking content
    const messagesWithThinkingSplit = computed(() => {
      return messages.value.map((m) => {
        if (m.role === "assistant") {
          if (m.content.includes("</think>")) {
            return {
              ...m,
              finishedThinking: true,
              think: m.content
                .split("</think>")[0]
                .replace("</think>", "")
                .replace("<think>", ""),
              content: m.content.split("</think>")[1],
            };
          } else {
            return {
              ...m,
              finishedThinking: false,
              think: m.content.replace("<think>", ""),
              content: "",
            };
          }
        }
        return m;
      });
    });

    // Filter messages to only show user and assistant messages
    const filteredMessages = computed(() => {
      return messagesWithThinkingSplit.value.filter(
        ({ role }) => role === "user" || role === "assistant"
      );
    });

    // Utility function to stream async responses
    function streamAsyncIterator(reader) {
      const decoder = new TextDecoder("utf-8");
      return {
        async *[Symbol.asyncIterator]() {
          try {
            while (true) {
              const { done, value } = await reader.read();
              if (done) return;
              yield decoder.decode(value);
            }
          } finally {
            reader.releaseLock();
          }
        },
      };
    }

    // Function to handle chat API calls - DIRECTLY CONNECTING TO OLLAMA
    async function chat(payload) {
      // Connect directly to Ollama
      return fetch("http://127.0.0.1:11434/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "deepseek-r1:1.5b", // Use your installed model name
          streaming: true,
          options: {
            temperature: 0.1,
            repeat_penalty: 1.2,
            numa: true,
          },
          messages: [...payload.messages],
        }),
      });
    }

    // Form submission handler
    const handleSubmit = async () => {
      if (!input.value.trim() || loading.value) return;
      
      loading.value = true;
      
      const userInput = input.value;
      input.value = ""; // Clear input field immediately
      
      const messagesWithInput = [
        ...messages.value,
        { role: "system", content: premise.value },
        { role: "user", content: userInput },
      ];
      
      messages.value = messagesWithInput;

      try {
        const stream = await chat({ messages: messagesWithInput });
        if (stream.body) {
          let assistantResponse = "";
          const reader = stream.body.getReader();
          for await (const value of streamAsyncIterator(reader)) {
            const {
              message: { content },
            } = JSON.parse(value);
            assistantResponse += content;
            messages.value = [
              ...messagesWithInput,
              {
                role: "assistant",
                content: assistantResponse,
              },
            ];
          }
        }
      } catch (error) {
        console.error("Error in chat:", error);
        // Show error message to user
        messages.value = [
          ...messagesWithInput,
          {
            role: "assistant",
            content: "Sorry, there was an error processing your request. Please try again. Make sure Ollama is running locally at http://127.0.0.1:11434.",
          },
        ];
      } finally {
        loading.value = false;
      }
    };

    // Additional method to access data from internal systems (if needed)
    const fetchInternalData = async () => {
      try {
        const response = await fetch("http://localhost:3000/api/data");
        const data = await response.json();
        return data;
      } catch (error) {
        console.error("Error fetching internal data:", error);
        return null;
      }
    };

    // Additional method to perform actions (if needed)
    const performAction = async (actionType, params) => {
      try {
        const response = await fetch(`http://localhost:3000/api/actions/${actionType}`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(params),
        });
        return await response.json();
      } catch (error) {
        console.error(`Error performing action ${actionType}:`, error);
        return { success: false, error: error.message };
      }
    };

    return {
      messages,
      input,
      premise,
      loading,
      filteredMessages,
      handleSubmit,
      fetchInternalData,
      performAction
    };
  }
}
</script>

<style>
/* Additional styles for better appearance */
::-webkit-scrollbar {
  width: 8px;
}

::-webkit-scrollbar-track {
  background: #1e293b;
}

::-webkit-scrollbar-thumb {
  background: #334155;
  border-radius: 4px;
}

::-webkit-scrollbar-thumb:hover {
  background: #475569;
}
</style>

// app/routes/index.tsx
import { useState, useMemo } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/start";
import Markdown from "react-markdown";
import { Send, Loader2, User2, Bot, MessageSquare } from "lucide-react";

import { Input } from "../components/ui/input";
import { Button } from "../components/ui/button";

type Message = {
  role: "user" | "assistant" | "tool" | "system";
  content: string;
};

type MessageWithThinking = Message & {
  finishedThinking?: boolean;
  think?: string;
};

function useMessagesWithThinking(messages: Message[]) {
  return useMemo(
    () =>
      messages.map((m: Message): MessageWithThinking => {
        if (m.role === "assistant") {
          if (m.content.includes("</think>")) {
            return {
              ...m,
              finishedThinking: true,
              think: m.content
                .split("</think>")[0]
                .replace("</think>", "")
                .replace("<think>", ""),
              content: m.content.split("</think>")[1],
            };
          } else {
            return {
              ...m,
              finishedThinking: false,
              think: m.content.replace("<think>", ""),
              content: "",
            };
          }
        }
        return m;
      }),
    [messages]
  );
}

function streamAsyncIterator(reader: ReadableStreamDefaultReader<Uint8Array>) {
  const decoder = new TextDecoder("utf-8");
  return {
    async *[Symbol.asyncIterator]() {
      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) return;
          yield decoder.decode(value);
        }
      } finally {
        reader.releaseLock();
      }
    },
  };
}

export const Route = createFileRoute("/")({
  component: Test,
});

const chat = createServerFn(
  "POST",
  async ({ messages }: { messages: Message[] }) => {
    return fetch("http://127.0.0.1:11434/api/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "deepseek-r1:32b",
        streaming: true,
        messages: [...messages.filter(({ role }) => role !== "system")],
      }),
    });
  }
);

function Test() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setInput("");
    setLoading(true);

    const messagesWithInput: Message[] = [
      ...messages,
      { role: "user", content: input },
    ];
    setMessages(messagesWithInput);

    const stream = await chat({ messages: messagesWithInput });
    if (stream.body) {
      let assistantResponse = "";
      const reader = stream.body.getReader();
      for await (const value of streamAsyncIterator(reader)) {
        const {
          message: { content },
        } = JSON.parse(value);
        assistantResponse += content;
        setMessages([
          ...messagesWithInput,
          {
            role: "assistant",
            content: assistantResponse,
          },
        ]);
      }
    }
    setLoading(false);
  };

  const messagesWithThinkingSplit = useMessagesWithThinking(messages);

  return (
    <div className="flex flex-col min-h-screen bg-gray-900">
      <div className="flex-1 p-4 container mx-auto max-w-4xl space-y-4 pb-32">
        {messagesWithThinkingSplit
          .filter(({ role }) => role === "user" || role === "assistant")
          .map((m, index) => (
            <div
              key={index}
              className={`flex ${
                m.role === "user" ? "justify-end" : "justify-start"
              }`}
            >
              <div
                className={`max-w-[80%] rounded-lg p-4 ${
                  m.role === "user"
                    ? "bg-primary text-black"
                    : "bg-gray-800 text-gray-100"
                }`}
              >
                <div className="flex items-center gap-2 mb-2">
                  {m.role === "user" ? (
                    <User2 className="h-4 w-4" />
                  ) : (
                    <Bot className="h-4 w-4" />
                  )}
                  <span className="text-sm font-medium">
                    {m.role === "user" ? "You" : "AI"}
                  </span>
                </div>
                {m.think && (
                  <div className="mb-2 text-sm italic border-l-2 border-gray-600 pl-2 py-1 text-gray-300">
                    <Markdown>{m.think}</Markdown>
                  </div>
                )}
                {m.role === "assistant" && !m.finishedThinking && (
                  <div className="flex items-center gap-2 text-gray-400">
                    <Loader2 className="h-4 w-4 animate-spin" />
                    <span className="text-sm">Thinking...</span>
                  </div>
                )}
                <article
                  className={`prose max-w-none ${
                    m.role === "user"
                      ? "prose-invert prose-p:text-black prose-headings:text-black prose-strong:text-black prose-li:text-black"
                      : "prose-invert prose-p:text-gray-100 prose-headings:text-gray-100 prose-strong:text-gray-100 prose-li:text-gray-100"
                  }`}
                >
                  <Markdown>{m.content}</Markdown>
                </article>
              </div>
            </div>
          ))}
      </div>

      <div className="fixed bottom-0 left-0 right-0 p-4 bg-gray-800 border-t border-gray-700">
        <form onSubmit={handleSubmit} className="container mx-auto max-w-4xl">
          <div className="flex gap-2">
            <div className="flex-1 relative">
              <MessageSquare className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
              <Input
                className="flex-1 bg-gray-900 border-gray-700 text-gray-100 pl-10"
                value={input}
                disabled={loading}
                placeholder="Ask about your local deepseek..."
                onChange={(e) => setInput(e.target.value)}
              />
            </div>
            <Button
              type="submit"
              disabled={loading || !input.trim()}
              className="bg-primary hover:bg-primary/90"
            >
              {loading ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Send className="h-4 w-4" />
              )}
              <span className="sr-only">Send message</span>
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}
